spring:
  messages:
    basename: messages/messages   # internationalization
  test:
    database.replace: none
  thymeleaf:
    mode: HTML
  web:
    resources.cache:
      cachecontrol:
        max-age: 12h            # maximum time static resources should be cached

management:
  endpoints:
    web:
      base-path: /manage
      exposure.include: "*"

# Logging
logging.level:
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte.data.jdbc: DEBUG
  org.springframework.jdbc.core.JdbcTemplate: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: TRACE
  #org.springframework.web: DEBUG
  #org.springframework.context.annotation: TRACE
