# use test containers to spin up mysql
yugabyte:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:yugabytedb:2.7.0.0-b17://localhost/yugabyte
    username: yugabyte
    password: yugabyte
