spring:
#  datasource: # database init
#    #url: jdbc:postgresql://127.0.0.1:5433/petclinic?load-balance=true
#    url: jdbc:postgresql://127.0.0.1:5433/petclinic
#    username: petclinic
#    password: petclinic
  test:
    database.replace: none   # do not attempt to replace database with in-memory database
  thymeleaf:
    mode: HTML
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 12h    # maximum time static resources should be cached
  messages:
    basename: messages/messages # Internationalization

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

# Logging
logging.level:
  sql: DEBUG
  com.zaxxer.hikari: TRACE
  com.zaxxer.hikari.HikariConfig: DEBUG
  com.yugabyte.data.jdbc: DEBUG
  #org.springframework.web: DEBUG
  #org.springframework.context.annotation: TRACE
